#include <stdio.h>
#include <stdlib.h>
#include <string.h>
//  A senator will ban the nearest opposite party's senator behind him or farest
//  before him.
//  After banning action, the banned senator will be dequed, and the
//  banning senator will dequeue and append to queue end
char *predictPartyVictory(char *senate) {
  int len = strlen(senate), i;
  int *q1 = malloc(len * sizeof(int)), head1 = 0, end1 = 0; // D
  int *q2 = malloc(len * sizeof(int)), head2 = 0, end2 = 0; // R

  for (i = 0; i < len; i++)
    if (senate[i] == 'D')
      q1[end1++] = i;
    else
      q2[end2++] = i;

  while (end1 - head1 > 0 && end2 - head2 > 0)
    if (q1[head1] < q2[head2]) {
      head2 += 1;
      q1[end1++] = q1[head1++] + len;
    } else {
      head1 += 1;
      q2[end2++] = q2[head2++] + len;
    }

  return (end1 == head1 ? "Radiant" : "Dire");
}
int main() {
  char *s =
      "RDRDDRRRDDDDRRDRDDDDRRRRRDDDDDDRDRRRDRRRDRRDRDRRRDRRDRDRRDRRDDDRDRRRRDDR"
      "RRDRDRDRDDRRDRRDDRDRRRDRRDRRRDDRDDDDRRDDDDDDRDRRRDRDRDDDDRDRRRDDRRRDRDDR"
      "DRRDRDDRDDRRDRRRDRDDDRRRRRDRDDRRRRDRRDRDDRRRDDDRDDDRDRRRDRRDRDRRRRRDRDRR"
      "DDRDRRDRRDDDRDRRRDRDRRRRRRDRDDDDRRDRDDRRDDDDDRDDDRRDDRDDRDRRRDRDDRDDDDRD"
      "DDDDRRRDDDRRDRDRRRDDDDDRRDDRRDDDRRDRDDDRRDRDRDRRRRDRDRDDDRDRRDDDRDRDDRDD"
      "RDDRDDRDDRRDRRRRDRDRRDRRRRRDDDRDRRDDDRRRDDDDDRDDRDRRRDDRRRRDRRDRDRRDDDRD"
      "RRDRDRDRDDDRRDRRRDDRDDRRRRDRDDRRRRRDDRDRRRRRDRDDRDRRRDRRRRRDRRRDDRDDDRRR"
      "DDDRDRRDDRRDRRDRDRRRDRDDDDRDRRDDRRRRRDDDRDDDRRDDRRRDRDRRDRRRDRDRRDDRRRRR"
      "DDDDRDRDRDRDDDDDRDRDRRDDDRRDDDRRDDDDRDDDRDDRRDRDRDRRDRRRRDRDRRRDRRRDDRDD"
      "RRRRDDDDDRDDDRRRRDRDRRRRRDRDRDRRRRDRDDRDRRRDDDRDRRRDRRDRDRDRDRDDDDDDRDDR"
      "RRRRDDDRRDRRDRDRDDRRDRRRRDDRDRDDDDRDRDDRDRDDRDRDRRDDRRRRRRRRDDRRRDDRDRRR"
      "DDDRDRRDDDDDDRDRRRRDRDDRDRDRRRRRDDRRDRRRRDRRRRRDRRDDRDDRRDDDRDRRRRDDRDRD"
      "RRDRRDRRRRDDRDDRDDRDRDDRDRRRDRDDDDDDDRRRRDDDRRDRRRRDRRRRDDRRRDDDDRRRDRDR"
      "RRRDDDRRDRRDDRDRDRDRDRRRDRRDDRRRDRRRDRRRRRDRRDDRRDDRDDDDRDDRRRRDRRRDDRRR"
      "RRDDRDRRRDRRDRRDRDDRDRRRDRDRDDRDRDRRDRRRDRRRRDRRRRRRDRDDDDRRRDRDDRRRDDRR"
      "DDDDDDRDDDRRDDRDDRDRRDDRDRDDRRDRDRDDDRRRRRDDRDDDDDRDDDRRRRRRDRDDDDDDDDRD"
      "DRRDDDRDDDRRDDDDRRRDDDRDDDDRDRDDRDRDDDDDDRRRRDDRDDDDDDRDRDRRRDDRRRRRRDDD"
      "RRRDDRRDRRRDRRDDDDDDRRDDRDDDRRRRRRDRDDRRRRDDDRDDRDDDRDRRRRDDDRRDRDRDDRRD"
      "RRDRRRRRDDRRDDRRRDDRRRRDDRRDRDDRDDDRRRDRRRDDDDRRRRDDDRRDDRDRDRRRDDDDRRRR"
      "DRRRDDRDRRRRRRDRDDRDDRDRDDRRRRDRRRDDDRDDRRRDDRRRDDRDRDRRRRDDDDDRRRRDRRRD"
      "RRRDRDRDRDRRDRDRRDDDRDRDRDRRDRDRRRRDDDDRDDRDDRDRDRDRRDDDDRRRDDRRDRRDDRRR"
      "RRDRRRDRRDRDDDRDDRRRRRRDDRRDDRRDRDRRDDDDDDDRRRRRDRRRRDDDRRDDRRRDRDRDRDRR"
      "RRDRDRDDRRDRRDRRRRDRDRDDDDRRDRRRRRDRRRRRRDDDDRDDDDRDDDRDDRRRDRDRDDRDRDDR"
      "RDDDRRRDDDRDRRRRDRDRRRRDRRRRDDRDRRRRDRDDRDRDDRRDDDDRDDDRRDRDDRDDRDRDRRDD"
      "RRRRRRDRDRDRRRDRRRDRDRRDDDRDDRRDDDDDRRRRRRDDDDDRRDDRRRRRDDRRRDRDRDRRRRDD"
      "DDRDRRDRDDRRDRRRDRRRRDRRDDRRDRDRDRRRDDRRRRRDDRDRRDDRDDDRDDDDDDRDRRRDRDRD"
      "RRRRRDRDRRRRRRRRRDRRRDDRDRRRDRDRDRDDDDDDDDDDDRDRDDRRDDDRDRDRDDRRRDRRDRDR"
      "DRDRRDRDDRRRRRDDRDDDDRDRRRDDDDRRDDRRDRDDDRDDRRRRDDDDDDRDRRRDRDDRRRRRRDDR"
      "DRRDRDRRDRDRRRRDRDDDDRRRDRRDRDDDDDRRRRRRRRRDDDRRDRDRRRDDDDRRRRDDRRRDRDDD"
      "RDRDDRDRDRDDDRDRRDDRRDRRRRRDDDRRDRDDRRRDDRRDDDRRRDRRDRRDRDDDRRRRDRDDDRDD"
      "RRDRRDRDRRRRRDRRRDRDRDRRRDRRRDRRDDDDRRDRRRDRRDDRDRRRDDDDRRRRDRRRDRDRDRRD"
      "RRDRDDRRDDDDRDDRDRDDDDRRDDDRDDRDDDRDDDRDRDRDDRDRDRRDDDDRDRRRRDRDRDDRDDRD"
      "RDRDRRRRDDRDRDDRRRDRRRDDRDDRRDDRRDRDRRDDRDDDDRRRDRDRDRRDRDRDRRDRRDDRDRRD"
      "DRDDDRRDDDDDDRDDRDDDDDRDRRDDDDDRDRDRDRRDDDRRDDRRRDDDRDRRDDDDDDDRDRRDRRRD"
      "RRRRDDRRRDRDDRDRDRDDRDRRRDRDRDRRDRRRDRRRDDDRRRRRDRRDDRDDDDRDRDRRRRRDDDDR"
      "RDDRDRDRRRDDRDDRDRDRDDDRRDRRDDRDRDDRRDRDDDDRDRDDDDRDDRDRRDRDDRRRRDDDRRRR"
      "RDDRDRDDDRDRRDDDRRDRDDRDRRRRRDRDRRDDRDDRDRDRRDDRDDRRDRDDDDDRDDDRRDDDRDRR"
      "RRRRRDRRRDDDDDDRDRDDDDDRRDRDDDDDRRRDRDDRRRDDDDDDDRDRDRDDRRRRDDDDDDDRDDRR"
      "RRRDRRDDDDRDRDRDDRRDDRDDRDRDRRRRDRRRRRDDDRDDRDRDDRDDRDRRDRRRRRRRRRDRRDRD"
      "RRRRRRDRDRDRDRDRDDDDRRDRRDRRDDRRDRRRRDRDDRDDDDDRRDDRDRDDRRDRRRDRDRDDRRDR"
      "DRRDRDRRRRDRRDDDDRDDRRRRRRDDDRRRRDDDRRDRRRDDDDDDDRRDRDDRDRRRRDRRDDDRDRDR"
      "RRRRDDRRRDRRDRRRDRDDDRDRDRRDRDDDRRRRDRRRDRRRDRRDDRDRDDRRDRRRRDRRDRRDDDRR"
      "DDRRDRRRDDRDDDRRRRDRRDRDRRDRRRRRDDRDDRRRRDRDDRRDRDDRDDDDDRRRDRRDDDDRRDDD"
      "RRDDRDRDRRRDDDRRRRRRDDDDRDDDDDDRRRDDRDRDRDRRRDDDRRRDDDRRRRRDRDRDDRDDDDRR"
      "DDDRRRRDRRDRDDRDDDRRRDRRRRRRDRDRDRDRDDRDRRRDRDRDDRRRDRRRRDRDRDDRRRRDDDRD"
      "RDRDRDRRRRDDRDRDDDRRDDDRRDDDDRRDRDDDRDDDDDDRRDRDDDDDDDRDRDDRDDDDDRDDRRRR"
      "DDDRDRRRDDDDDDRRRDRRDRRRDRRRRRRDDDDRDRRRRRRDRDDDDRDDDRRRRRRRDDDRRRRRDRRR"
      "DDRRRRDDRRRDDDDRDDDDRRRRDDRDRDRRDDDDDRRRDDRRRRRRRDRDDRRDRRRRDDDDRRDDRDDD"
      "DDDRRDDDRRDRRDDDRRDRDRRDRDDRDDRDRRRDDDRRDDRRDRDDDRRDRRDRRDRRDRRRDRRRDDRR"
      "RDDDRDDRRDDDRRRRDRRRRRRDRRRDDRDRRDDRRRRDRRRDRDDDDRRDRDRDRRRDRDDDDRDRDDDD"
      "RDRRRRRRDRDRDDDDDRRDDDDDRRDDDRRRRRRDRRRRRRRRDRRRRRRRRDDRRDRDRRDDDDDRDRRR"
      "RRRRRDRDRRDRRDRDDRDRRRRDDDDRDRRDRDDRDRDRRRDDRRRRDDDDRDDDDRDRRDDDDDDRDDDD"
      "DDRDDDRDRDRDRDRDDRRDRDDDRDDDRDDRDDDDRRDDRDRDDDRRDRRRDRRDDRDDRRDDRDRRRRDD"
      "RDRDDRRDDDDRRDRDRDDRDDDRDRRRRDDRRDDDDRRDRRDDRDRDDDDRDDRDRDRRDDDDDRRRRDDD"
      "DRRDDDRRDRRRDDDDRDDDRDRDDRDDRRDDRDDRDDDDDDRDRDDRRDDDRDDRRRDRDDDRDRRRDDDR"
      "DRRDRRRDRDDDRDDRRRDRDRRRDDDRDDDRRDRRDDRDRRRRDDDDDDDRRRDDRRDDRRRDRDRDDRDR"
      "DRDDRDDDRDRRRRDDDRDRDDRRDRRDDRDDRDRDRDRRRDDRDRDDDRDRRRDRDRRDRRRDDRDRRRDD"
      "RRDDDRRDDDDRRRRRRDRRDDDRRRDDDRDRDDDRDRRRRDRDDDRDDDRRRRRDRDDRRDRDDRDRDDRR"
      "DDRDDDDRRRDDRDRRRRDRRDRDDRDRRRDDDRDRDRRDDDRRRDDRDRDDRDRDDDRRRRDRDRRDRDRR"
      "RDRDDRDRDRDDRRRRRDRRRRRDDDDDDRRDDRDDRRRDRRDRRDRRDDDDRRRRRDDRRDRRRRDRDDDD"
      "RDDDDRRRRRDDDRDDRRDRDDDDRDRRDRRRRDDRRRDRRRRDDDDRDDDDDDRRDRDRDRDDDDDDRDDR"
      "RRRRDDRDRDRDRRDDDDRRDRRRRRRDRRDDRRDDRRRDDRRDDDDDRDRRRDDRRRRRRDRDRRDRRDRR"
      "RRDDDRDDDRRRDRDDRRRDDRDDRRRRRDRDRDDRRDRDRRDDRRDRDRDDRDDRRRRRRRDRRDRDDRDD"
      "RDRRRDDDDRDRRDRDDDRRDDRRDRDRDRRRDDDRDRDRRDDDRRDRRDDRDDDDRDRDDRDDDRDRDDDD"
      "DDRDDRDDRDDDDDDRRRRDDRRRRRDDRDRDRRRDDDRRRDRRRRDDRRDRRRDDRDRDRRDRRRRDRDRD"
      "RRDDRRRDDRDRRRRDDRRRRDRRDDDRDRDDDRDRRRRDRRDDDRRRRDRRRRRDRDDDDRDDDDRRDRDR"
      "DDDRDRDRRDRDRDRDRRRRRRDRRDRDRDDRDRRRDRRRDRRDRRDDRRRDDRDRDDDDRRDDDRDRDRDR"
      "DDDRDDRRRDRDRRRDDRRDRRDDDDDDRDDDDDRRRDDDDRDDRRRDRDRDRRDDRDRDDDRRDRDDRRRR"
      "RRRRDRRRDDRDDRRDDRDDRRRRRDDDDRRDRDDRDDDRDDRDRRRRDDRDDRDRRDDRRRDRDDRRRDDD"
      "RDDDDDDRRRDRRDRRRDDDDRRRDDDRDRRDRRRDDDDDRDDRDDRRDRRRRDDRDDRRRRDDDRRDDDDD"
      "RRRDDDRRDDRRDDDDRRDRRDDRRRDRRDRDDRRRRDRDRDDDDRRDDRRRDDRDRDDRDDRDRDDRDDRR"
      "DRRDDDDRDDDRDRRDDDDDRRRRRDDDDRDDRDRDDRDRRRRRRDDRRRRRRDDRDRRRDDRDRDRDDRRR"
      "RDDRRRRRDDRRRDRRRRDDDDDDRDRDRDDDRRRRDDDDDDDRDDRRRDRDDRRRDRRDDRDDRDRRRDRR"
      "DRRDDDDDRDDDRRDDRDDDRRRRDDRRDDDDDDDRRDDDDRDRRDRDRRDDRRRRDRDDRRRDDRRRDRRR"
      "DRDDDDDDRDRRDDRRDRRDRRDDDDDRDRDRDRDDRDDRRDRDRRRRRRDRDRRDRRRDDRDDDRDDDRDR"
      "RRDDRDDRRDRDDDRRRRRDRDRDRRRDRDDDRDDRRRDDRDRDRDRDDRDRDDDRRDDDDRDRDRRRDRDR"
      "RRDDRDRDDRRDDRDRDDRRRDRRRRRDDDDDRRDRRRDDDRDDDDRDRRRDDRDDRRDDRDRDRDDDRDDR"
      "DRDDRDRDRRDRDDDDRDRDRDRDDDRDDRDDDRRDRDDDRDRDDDRRRRDDDRRRRRDRRDRRDDRRDRRD"
      "DRRDRRRRDRRDDRDDRDDRDRDRRRRDDRDDRDDRRDRRRDDRRRRRDRDRRDRRRRRDRRDRDDDRDDRD"
      "DDDRDRDDDRDDRDDDDDRDDRRDRDDDDRDDRRDRRDRRDDDDRDDRDRRDDDDDRRRRRDRDDDDDDDRR"
      "RDRRDDDDDDDRRRDRRRRDDDRRRRDRDDDDDDDRDDRRRRRDRDDRDDDRDRDDDDRRRRDRDRRRDDDR"
      "DDRDDRDRRDDRDDDDDDDDRRRDDRDDRRRDRRRRDDDDDRRDRDRRDDRDDRDDRDRDDDRRDDRRDDDD"
      "DDDDRDRRDRDDDDRDDDRRDRDDDRDRDDDDRRRDDDRDDDRRRRRRDRDRDRRRRDRDRRRDRRRRRRRD"
      "DDDRRRDRRDDRDRDRDRRRDRDRDDRDDRDRDRDRRDRDRDRDRRRRRDDRDRDRRDDRRDDRDRDRRDDR"
      "DDDDRRDDDDRRDRRDDDDRDRRRRRRRRDDRRDDRDDRRDRRDDDDDRRRRDDDDRRRDRDRDRRDDDRDD"
      "DDDRRRRRRDRDDDRRRDDDDDDDDRDRRDRRDDDDDDDRDRRRRDRRDRRRRRRRRDRDRRDRRDRDRRRR"
      "RDRDRRDRDDDDRRRRDDRDRRDRRRDRDRDDDRDRRDRRRRRDRRDRRRDDDDRDRDRRDDRDRRRRDRRD"
      "RDDDDRRDRDDRDRRRRRRRRRDRRDDRDDRRRDDDDRDDRRRRRRDRDRRRDDDDDDRRRDRDRRRRDRDR"
      "DRRRRRDDRRRRRRDRRDDDRDDDDRDDRRDDDDDRRRRRDRDRRRDDDDRDRDDDDDRRRRRRRRDDDRDD"
      "RDDRDRRDRDRRRDDRRDRRRRRDRRDRRDDDDDDDRDRRRDDRRRDRRDRRRDDDRDDDDDDRRRDDRDDD"
      "DRRRDDRDRRRDRDDRDRRDRDRRDDRDDRDDDDDDRDRRDRRRDRDRRDDRRRDRDRRDDRRDDRRRRRRD"
      "RDRRRRRRDDRDRDDRDRDRRDRRDDRDDDDDDRDRRDRDRDDRRDRRDRDRDRRDRDDRRDDDDDRRRRDR"
      "RDDDDRRDDRRDDDDRRDRDRDRRRRRDRDRRDRRDDDDRDDDDRRRDRRDRRRRRDRRDDRDRDDDDDDDR"
      "RDRRRDDRDDRRRDRDRDRRDRDRRRDRRRDDRDRDDDDDRRRDDDDRRRRDDDRDDRRRRRRRDDRDRRDR"
      "DDDRRDRRDRDRRDRDDRRRDDRRRDDRRDDRRDRRDDDRRRRDDRDDRRRDRDDDRDDDRDDRRDDRDDDD"
      "DRRDDDRDRDRDDRRDRDDRRRRDRDDDRRRRRDRRDDRRDDRRDRRRDDDRDRDDRRRRDDDRDDRRRRRR"
      "DDRDDRRRDRRDRDDDDDRDDDRRDRDRDRRRDRRRDRRDRRDDDRDDDDRRDRDRRDDRDRRRRDDRDDRR"
      "DDRDRRRRRRDDDDDRDRRDRRDDDDRDRRRDRRDRRDDDDRDRDRDDRDRRRRRRRDRDDDRRDRRDDDRR"
      "RRDDDRDDDRRDDRRRDRDRDRDDRRDDDRDRRDDRRRDDDDRDRDDDRDRRDDDRRRRDDRRRDRRDRDDR"
      "DRRRRRRRDDRDDRDRRDRRDDRDDRDDRRRRRRRRDRRDRRRRDRDDDRDRDDRDRRRDRRRRDDRDRDDR"
      "DDRDDDDDDRDRDDRRDDDRDDDDRRDRRDRDDRRDRRDDRRDRDDDDDDDRRDDDDDDDRRRRDRDRDDDD"
      "RDRRRRRRRDRDDRDDRDRDRDRRDDRRRDDRDRDRRDRDDDRRRRDRRRRDRRRDDRDRDDDRRDRDDDDD"
      "DRRRRRDDRRDDRRDRDDRDRRRRDRRRRRRRRDDRDRDRDDRDRRDRRDRRRRRDDRDDRDRDRRRDRDDD"
      "RRDDRDRDRDRRDRDRRDRRDDDRDRDDDRRRRRRRDDRDRRRRDDDDDDDDDRDDDRRRRRRRRDRDRRRR"
      "RDRDDDRDRDRDRDRDRRRDRDDRDDRDRDDRDDDRDDDRRRDDDRRDRRDDDRRRRRDDDDRRDRRRDRDD"
      "DDRRRRDRDRRDDDDRDDRRRDRDDRDDDRRDRDRDRRDDDDDDDDRRDDRDRRDRRRRDRDDDRRRRRRDD"
      "RRDDDRRRRDDRDDDRRDDDDDRDDDDRDDDRRRRDDDDRDRRDRRDRRRDRRRRDRRRRRDDRRRDRRDDR"
      "DDDRDRRDRDDDDRRRRRDDRRDRDDDDDRRDDRDDDDDDDRDRRRDRRDRDRRRDDDRRRRDRRDDRRDDR"
      "DRDRDRRRRDDRRRRRRRRDRRRDDRRRDDRDDRRDDRRRRDDRDRDDDRDDDRRRDDDRDDDRRDRRDDRD"
      "DDRDRRRDDRDRDDRDDRRRRRDDDRDDRDDRRRRRRRDRRRRRDDDRDRDRDRDRDRRRRDRRRRDRRDRR"
      "RRDDRRDDRDRRDRDRRDRRRDDRDRRRDRDDRDDRRDDRDRRRRRRRRRDRRRDDDRRRRRRRDRRRRDRR"
      "DDDRDRDRRDDDDDRRDDRRDDDDDRRDRDDDRDDDDDDRDRRRDRRDRDDDDRDDRRDRDDDDRRRDRRRD"
      "RDRRDRRDRRRDDRDDRDRRRDRRRDRRRDDRDRRDDDDDDDRRRRDRRRRRRDDRRRRDDRRRDRRDDRDR"
      "RDRDDDRRRRDDDDRDDDRDDRRRRDRRDDRRDDDRRRDDRDRDDDDRRRRRRRDDDDRRDDDDDDDRRRRR"
      "DRDRDDDRRDDRRRDDRDDDDDRDRDRDDRRDDRRDDRDDRRRRRRRRRDRDRRDDRRDRDRRDRRDRDRDD"
      "DDDRDDRDDDRRRRRDRDDRDRDDDDDDRRRRRRDRDDRDRDRRRRDDRDRRRRDDDDDRRDDRRDRDDRDR"
      "RDDRDDDDDDDDRDRDDRDRRDRDDRRRRDRRDDRRDRDRDRRDDRRRRRRDDDRRDRDDRDRDDRRRDDRR"
      "RRRDDRRRDRDRDDRDRRDDRRRRRDDDRDRRDRRRRDDDRRDDDDRDDRRDDDRDDDRRDDRDRRRRDRDD"
      "DRDRRRDDRDDDDDDDDDRDDDDDRRDRDDDDDDRRDDDDDRDRDRRRDRRDRDDRRRDDDRDDDDRDRDRR"
      "DRDDDRDDDDDRDRDRDRDRRRRDDDRRDRRRRDRRDRRRDDRRRRRDRDRDRRDRRRRRDRRRRRDRDRDR"
      "DDDDDDDRDRDRDDDRRRDRRDRRRDDRRDRRDRRRRRRDDRRDRRDRRDDDRRRRRDRDRDRDRRDDDRDR"
      "DRRDRRDDRDRRRDDDDDDRRDDRRDDRDRRRRDRDRDDDDDDDRRRRRDRRRRRDRRRDDDDDRDRDDDRD"
      "RRDRRDRDRRRRDDRDDRRDRDDDDDDRDRDRRDDRDRRRDDRRRDRRRRRDRRDRDRDDDRRDDDRDDDDR"
      "RRDRDRRRDDRRRDRDDRDDRRRDRRRDRRDRRRRRDDDRDDDDDRRRRRDRRRRRRDRDDRDRRRRRDRDR"
      "RRRRDRRRRDDDDRDRDRDDRRDDDDDRRRDDRDDDRDDRRDDRDDDDRRRDDDDDDRRDDDDDRDRDRDRD"
      "RRDDRDRDRDDRRRRRDRRRRRRRRDRDDRRRDDRDRRRRDRDRRDDRRDDDRRDDRRDRRDRRDRDDDDDD"
      "RRDDDRRDRRDDDDDDRDRDDDDDDDRDRDRDRRDRRDDDDDRDRDDDRDDDRRDRRRRRDDRRRRDRRRDD"
      "RRRDDRDDDDDDRDDDRRDDDRDRDRDRRRRDRDDDDDDRRRDDDDDDDDDRRDDDDRRRDDRRDDDDDDRR"
      "RDDRRRDRDDRDDRRRDRRDRDRRRDRRDRRRRDRDDDRDDDRDRDDDDRRRDDRDRDRRDRRDRRDDDRRR"
      "DRDDRRDRDDRDDDRRRDRDRRRRDRDRDDRDDRDDDDRDRRDRRDRDRRDDDDRDRDRRDRDDDDRRDRRR"
      "DDDDRRDRRRRRRDRRDRRDDDRRDRDDDRRDRDDDRRRRDDRDRDDRRDRRRDRDDRRDDDDDRDRRDRDR"
      "DDRRRDDDDRDDRDRDRDRDDDRDRDRRRDRRDDDRRRRRDRDDRRRRRDDDDRDDDDDDDRRDRRDDDDRR"
      "RDRDRRDDRRDDRDDRDDDDRRRDDRDRDDRDDRDDDDRRDRRRRDDRRRDDRDDDDRDDDRRRRDDRDDDR"
      "RRRRRRDDRRRDDDDRRRRDRDDRRRDDDDRDRDRRDDDDRRDDRDDDRRRDDRDRRDDDRRDDDDDDRDDD"
      "RDDRDDDRRRRRRDDRRRRDDDRRRRRDRRDRDRRRRRDDRRRDDRDDRRRRDDRDDRRRDRRRRDDRDRDR"
      "DDRDRRDRRDDDRDDDDDRDRRRDRDRRRRDRRDRRRDRDDDRRRRDRRDDRRDRDRRDRRRRDRRRDRDDD"
      "DDRDRDDRDRDDDRRDRDDDDDDDRDDRDDRRRRRRRDDDRDDDDRDDRDDDDDDRDDDDDDDDDDRDDRDR"
      "RDRRRDDRDDRDDDDDRRRRDDRRDDRDDDDDDDDDDRRRRRDDDRDDDRRRDDRRRDRRDDDRRRRDRRDR"
      "RRRDDRRDRDDDDDRRDRRRDRRDRDDRDDDRRDDRRRDDDRRRDRDRDRRDRDRDDRRDRRRD";
  printf("%s\n", predictPartyVictory(s));
  return 0;
}
